# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:

  # Backend
  - package-ecosystem: 'npm'
    directory: '/frontend'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'sveltekit'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    open-pull-requests-limit: 5

  # Frontend
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'update'
      include: 'scope'
    open-pull-requests-limit: 5
