---
services:
  riven-frontend:
    image: spoked/riven-frontend:latest
    container_name: riven-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    #network_mode: host
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - ORIGIN=http://localhost:3000
      - BACKEND_URL=http://127.0.0.1:8080
      - TZ=America/New_York
    depends_on:
      riven:
        condition: service_healthy
      
  riven:
    image: spoked/riven:latest
    container_name: riven
    restart: unless-stopped
    ports:
      - "8080:8080"
    #network_mode: host
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - RIVEN_DATABASE_HOST=postgresql+psycopg2://postgres:postgres@riven_postgres/riven        #Postgres database
      #- RIVEN_DATABASE_HOST=postgresql+psycopg2://postgres:postgres@localhost/riven            #nework_mode: host {use @localhost}
      #- RIVEN_DATABASE_HOST=sqlite:////riven/data/media.db                                     #SQLite database
    healthcheck:
      test: curl -s http://localhost:8080 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - ./riven-data:/riven/data
      - /mnt:/mnt
    depends_on:
      riven_postgres:
        condition: service_healthy
        
  riven_postgres: # Add #before all {riven_postgres} lines when using SQLite
    image: postgres:16.3-alpine3.20
    container_name: riven-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: riven
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    #network_mode: host