services:
  riven:
    build:
      context: .
      dockerfile: Dockerfile
    image: riven:dev
    container_name: riven
    restart: unless-stopped
    network_mode: host
    tty: true
    environment:
      # Docker
      - PUID=1000
      - PGID=1000
      - ORIGIN=${RIVEN_ORIGIN:-http://localhost:8080}
      - TZ=UTC
    volumes:
      - ./data:/riven/data
      - /mnt:/mnt