---
services:
  riven-frontend:
    image: spoked/riven-frontend:latest
    container_name: riven-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - ORIGIN=http://localhost:3000
      - BACKEND_URL=http://127.0.0.1:8080
      - TZ=Europe/Amsterdam
    depends_on:
      riven:
        condition: service_healthy
      
  riven:
    image: spoked/riven:latest
    container_name: riven
    restart: unless-stopped
    ports:
      - "8080:8080"
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - RIVEN_DATABASE_HOST=sqlite:////riven/data/media.db
    healthcheck:
      test: curl -s http://localhost:8080 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - ./riven-data:/riven/data
      - /mnt:/mnt