# This is a full setup for Riven with Plex, Overseerr, Zilean, and Prowlarr.
# This compose assumes you already setup rclone and zurg. See notes below!

## Notes:

# Zurg & Rclone will have to be supplied as well and visible to Riven as well as Plex.
# Rclone should be mounted to: /mnt/zurg (optional directory)
# You will need to set the rclone_path in riven to use the `/mnt/zurg/__all__` dir though
# so that Riven can see all the torrents from their parent directory.

services:
  riven-frontend:
    image: spoked/riven-frontend:latest
    container_name: riven-frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - ORIGIN=http://localhost:3000  # Set to IP or FQDN of the server
      - BACKEND_URL=http://riven:8080
      - DIALECT=postgres
      - DATABASE_URL=postgres://postgres:postgres@riven-db/riven
      - TZ=America/Los_Angeles
    depends_on:
      riven:
        condition: service_healthy

  riven:
    image: spoked/riven:latest
    container_name: riven
    restart: unless-stopped
    ports:
      - 8080:8080
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - RIVEN_FORCE_ENV=true # Forces the use of env vars to be always used!
      - RIVEN_SYMLINK_RCLONE_PATH=/mnt/zurg/__all__ # This is the path of your rclone mount point
      - RIVEN_SYMLINK_LIBRARY_PATH=/mnt/plex # This is the path that symlinks will be placed in
      - RIVEN_DATABASE_HOST=postgresql+psycopg2://postgres:postgres@riven-db/riven
      - RIVEN_DOWNLOADERS_REAL_DEBRID_ENABLED=true
      - RIVEN_DOWNLOADERS_REAL_DEBRID_API_KEY=xxxxx # set your real debrid api key
      - RIVEN_UPDATERS_PLEX_ENABLED=true
      - RIVEN_UPDATERS_PLEX_URL=http://plex:32400
      - RIVEN_UPDATERS_PLEX_TOKEN=xxxxx # Set your plex token
      - RIVEN_CONTENT_OVERSEERR_ENABLED=true
      - RIVEN_CONTENT_OVERSEERR_URL=http://overseerr:5055
      - RIVEN_CONTENT_OVERSEERR_API_KEY=xxxxx # Set your overseerr token
      - RIVEN_SCRAPING_TORRENTIO_ENABLED=true
      - RIVEN_SCRAPING_ZILEAN_ENABLED=true
      - RIVEN_SCRAPING_ZILEAN_URL=http://zilean:8181
    healthcheck:
      test: curl -s http://localhost:8080 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - ./riven/data:/riven/data
      - /mnt:/mnt
    depends_on:
      riven_postgres:
        condition: service_healthy

  riven_postgres:
    image: postgres:latest
    container_name: riven-db
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: riven
    volumes:
      - ./riven-db/data:/var/lib/postgresql/data/
      - ./riven-db/pg-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ## Zilean (optional scraper service)
  zilean:
    image: ipromknight/zilean:latest
    restart: unless-stopped
    container_name: zilean
    tty: true
    ports:
     - 8181:8181
    volumes:
      - ./zilean/data:/app/data
    environment:
      Zilean__Database__ConnectionString: "Host=zilean-db;Port=5432;Database=zilean;Username=postgres;Password=postgres"  # Point to zilean-db
      #Zilean__Dmm__ImportBatched: "false"         # Allows enabling batched import - this is for low-end systems.
      #Zilean__Dmm__MaxFilteredResults: 500       # Allows changing the maximum number of filtered results returned by the DMM API. 200 is the default.
      #Zilean__Dmm__MinimumScoreMatch: 0.97       # Allows changing the minimum score match for the DMM API. 0.85 is the default. Values between 0 and 1 are accepted.
    healthcheck:
      test: curl --connect-timeout 10 --silent --show-error --fail http://localhost:8181/healthchecks/ping
      timeout: 60s
      interval: 30s
      retries: 10
    depends_on:
      zilean-db:
        condition: service_healthy

  zilean-db:
    image: postgres:latest
    container_name: zilean-db
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zilean  # Database for Zilean
    ports:
      - 5432:5432
    volumes:
      - ./zilean-db/data:/var/lib/postgresql/data/
      - ./zilean-db/pg-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ## Prowlarr (optional indexer service)
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./prowlarr/config:/config
      - ./prowlarr/downloads:/downloads
    restart: unless-stopped

  ## Plex (optional plex service)
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    ports:
      -  32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - VERSION=docker
    volumes:
      - ./plex/config:/config
      - /mnt:/mnt
    devices:
      - "/dev/dri:/dev/dri"

  ## Overseerr (optional content service)
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./overseerr/config:/config
    ports:
      - 5055:5055

