services:
  riven:
    build:
      context: .
      dockerfile: Dockerfile
    image: riven:dev
    container_name: riven
    restart: unless-stopped
    network_mode: host
    tty: true
    environment:
      # Docker
      - PUID=1000
      - PGID=1000
      - ORIGIN=${RIVEN_ORIGIN:-http://localhost:8080}

      # Custom Env Variables - Separate from settings model
      - RIVEN_FORCE_ENV=false
      - MAX_WORKERS=${MAX_WORKERS:-1}

      # Riven Settings
      - RIVEN_VERSION=${RIVEN_VERSION:-0.6.4}
      - RIVEN_DEBUG=${RIVEN_DEBUG:-false}
      - RIVEN_LOG=${RIVEN_LOG:-false}
      - RIVEN_PLEX_UPDATE_INTERNAL=${RIVEN_PLEX_UPDATE_INTERNAL:-120}
      - RIVEN_PLEX_TOKEN=${RIVEN_PLEX_TOKEN}
      - RIVEN_PLEX_URL=${RIVEN_PLEX_URL:-http://plex:32400}
      - RIVEN_SYMLINK_RCLONE_PATH=${RIVEN_SYMLINK_RCLONE_PATH:-/mnt/zurg/__all__}
      - RIVEN_SYMLINK_LIBRARY_PATH=${RIVEN_SYMLINK_LIBRARY_PATH:-/mnt/library}

      # Downloaders
      - RIVEN_DOWNLOADERS_REAL_DEBRID_ENABLED=${RIVEN_DOWNLOADERS_REAL_DEBRID_ENABLED:-false}
      - RIVEN_DOWNLOADERS_REAL_DEBRID_API_KEY=${RIVEN_DOWNLOADERS_REAL_DEBRID_API_KEY:-}
      - RIVEN_DOWNLOADERS_TORBOX_ENABLED=${RIVEN_DOWNLOADERS_TORBOX_ENABLED:-false}
      - RIVEN_DOWNLOADERS_TORBOX_API_KEY=${RIVEN_DOWNLOADERS_TORBOX_API_KEY:-}

      # Content
      - RIVEN_CONTENT_OVERSEERR_ENABLED=${RIVEN_CONTENT_OVERSEERR_ENABLED:-false}
      - RIVEN_CONTENT_OVERSEERR_API_KEY=${RIVEN_CONTENT_OVERSEERR_API_KEY:-}
      - RIVEN_CONTENT_OVERSEERR_URL=${RIVEN_CONTENT_OVERSEERR_URL:-http://overseerr:5055}
      - RIVEN_CONTENT_OVERSEERR_USE_WEBHOOK=${RIVEN_CONTENT_OVERSEERR_USE_WEBHOOK:-false}
      - RIVEN_CONTENT_OVERSEERR_UPDATE_INTERVAL=${RIVEN_CONTENT_OVERSEERR_UPDATE_INTERVAL:-60}
      - RIVEN_CONTENT_PLEX_WATCHLIST_ENABLED=${RIVEN_CONTENT_PLEX_WATCHLIST_ENABLED:-false}
      - RIVEN_CONTENT_PLEX_WATCHLIST_RSS=${RIVEN_CONTENT_PLEX_WATCHLIST_RSS:-}
      - RIVEN_CONTENT_PLEX_WATCHLIST_UPDATE_INTERVAL=${RIVEN_CONTENT_PLEX_WATCHLIST_UPDATE_INTERVAL:-60}
      - RIVEN_CONTENT_MDBLIST_ENABLED=${RIVEN_CONTENT_MDBLIST_ENABLED:-false}
      - RIVEN_CONTENT_MDBLIST_API_KEY=${RIVEN_CONTENT_MDBLIST_API_KEY:-}
      - RIVEN_CONTENT_MDBLIST_UPDATE_INTERVAL=${RIVEN_CONTENT_MDBLIST_UPDATE_INTERVAL:-300}
      - RIVEN_CONTENT_MDBLIST_LISTS=${RIVEN_CONTENT_MDBLIST_LISTS:-[]}
      - RIVEN_CONTENT_LISTRR_ENABLED=${RIVEN_CONTENT_LISTRR_ENABLED:-false}
      - RIVEN_CONTENT_LISTRR_API_KEY=${RIVEN_CONTENT_LISTRR_API_KEY:-}
      - RIVEN_CONTENT_LISTRR_UPDATE_INTERVAL=${RIVEN_CONTENT_LISTRR_UPDATE_INTERVAL:-300}
      - RIVEN_CONTENT_LISTRR_MOVIE_LISTS=${RIVEN_CONTENT_LISTRR_MOVIE_LISTS:-[]}
      - RIVEN_CONTENT_LISTRR_SHOW_LISTS=${RIVEN_CONTENT_LISTRR_SHOW_LISTS:-[]}
      - RIVEN_CONTENT_TRAKT_ENABLED=${RIVEN_CONTENT_TRAKT_ENABLED:-false}
      - RIVEN_CONTENT_TRAKT_API_KEY=${RIVEN_CONTENT_TRAKT_API_KEY:-}
      - RIVEN_CONTENT_TRAKT_UPDATE_INTERVAL=${RIVEN_CONTENT_TRAKT_UPDATE_INTERVAL:-300}

      # Scrapers
      - RIVEN_SCRAPING_AFTER_2=${RIVEN_SCRAPING_AFTER_2:-2.0}
      - RIVEN_SCRAPING_AFTER_5=${RIVEN_SCRAPING_AFTER_5:-6}
      - RIVEN_SCRAPING_AFTER_10=${RIVEN_SCRAPING_AFTER_10:-24}
      - RIVEN_SCRAPING_TORRENTIO_ENABLED=${RIVEN_SCRAPING_TORRENTIO_ENABLED:-false}
      - RIVEN_SCRAPING_TORRENTIO_FILTER=${RIVEN_SCRAPING_TORRENTIO_FILTER:-sort=qualitysize%7Cqualityfilter=480p,scr,cam}
      - RIVEN_SCRAPING_TORRENTIO_URL=${RIVEN_SCRAPING_TORRENTIO_URL:-https://torrentio.strem.fun}
      - RIVEN_SCRAPING_KNIGHTCRAWLER_ENABLED=${RIVEN_SCRAPING_KNIGHTCRAWLER_ENABLED:-false}
      - RIVEN_SCRAPING_KNIGHTCRAWLER_URL=${RIVEN_SCRAPING_KNIGHTCRAWLER_URL:-https://knightcrawler.elfhosted.com}
      - RIVEN_SCRAPING_KNIGHTCRAWLER_FILTER=${RIVEN_SCRAPING_KNIGHTCRAWLER_FILTER:-}
      - RIVEN_SCRAPING_JACKETT_ENABLED=${RIVEN_SCRAPING_JACKETT_ENABLED:-false}
      - RIVEN_SCRAPING_JACKETT_URL=${RIVEN_SCRAPING_JACKETT_URL:-http://jackett:9117}
      - RIVEN_SCRAPING_JACKETT_API_KEY=${RIVEN_SCRAPING_JACKETT_API_KEY:-}
      - RIVEN_SCRAPING_JACKETT_LIMITER_SECONDS=${RIVEN_SCRAPING_JACKETT_LIMITER_SECONDS:-60}
      - RIVEN_SCRAPING_PROWLARR_ENABLED=${RIVEN_SCRAPING_PROWLARR_ENABLED:-false}
      - RIVEN_SCRAPING_PROWLARR_URL=${RIVEN_SCRAPING_PROWLARR_URL:-http://prowlarr:9696}
      - RIPEN_SCRAPING_PROWLARR_API_KEY=${RIPEN_SCRAPING_PROWLARR_API_KEY:-}
      - RIVEN_SCRAPING_ORIONOID_ENABLED=${RIVEN_SCRAPING_ORIONOID_ENABLED:-false}
      - RIVEN_SCRAPING_ORIONOID_API_KEY=${RIVEN_SCRAPING_ORIONOID_API_KEY:-}
      - RIVEN_SCRAPING_ORIONOID_LIMITCOUNT=${RIVEN_SCRAPING_ORIONOID_LIMITCOUNT:-5}
      - RIVEN_SCRAPING_ANNATAR_ENABLED=${RIVEN_SCRAPING_ANNATAR_ENABLED:-false}
      - RIVEN_SCRAPING_ANNATAR_URL=${RIVEN_SCRAPING_ANNATAR_URL:-https://annatar.elfhosted.com}
      - RIVEN_SCRAPING_ANNATAR_LIMIT=${RIVEN_SCRAPING_ANNATAR_LIMIT:-2000}
      - RIVEN_SCRAPING_ANNATAR_TIMEOUT=${RIVEN_SCRAPING_ANNATAR_TIMEOUT:-10}
      - RIVEN_SCRAPING_TORBOX_SCRAPER_ENABLED=${RIVEN_SCRAPING_TORBOX_SCRAPER_ENABLED:-false}
      - RIVEN_SCRAPING_MEDIAFUSION_ENABLED=${RIVEN_SCRAPING_MEDIAFUSION_ENABLED:-false}
      - RIVEN_SCRAPING_MEDIAFUSION_URL=${RIVEN_SCRAPING_MEDIAFUSION_URL:-https://mediafusion.elfhosted.com}
      - RIVEN_SCRAPING_MEDIAFUSION_CATALOGS=${RIVEN_SCRAPING_MEDIAFUSION_CATALOGS:-["prowlarr_streams","torrentio_streams"]}

      # Ranking
      - RIVEN_RANKING_PROFILE=${RIVEN_RANKING_PROFILE:-default}
      - RIVEN_RANKING_REQUIRE=${RIVEN_RANKING_REQUIRE:-[]}
      - RIVEN_RANKING_EXCLUDE=${RIVEN_RANKING_EXCLUDE:-["threesixtyp"]}
      - RIVEN_RANKING_PREFERRED=${RIVEN_RANKING_PREFERRED:-[]}
      
      # Custom Ranks
      - RIVEN_RANKING_CUSTOM_RANKS_UHD_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_UHD_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_UHD_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_UHD_FETCH:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_UHD_RANK=${RIVEN_RANKING_CUSTOM_RANKS_UHD_RANK:-120}
      - RIVEN_RANKING_CUSTOM_RANKS_FHD_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_FHD_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_FHD_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_FHD_FETCH:-true}
      - RIVEN_RANKING_CUSTOM_RANKS_FHD_RANK=${RIVEN_RANKING_CUSTOM_RANKS_FHD_RANK:-100}
      - RIVEN_RANKING_CUSTOM_RANKS_HD_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_HD_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_HD_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_HD_FETCH:-true}
      - RIVEN_RANKING_CUSTOM_RANKS_HD_RANK=${RIVEN_RANKING_CUSTOM_RANKS_HD_RANK:-80}
      - RIVEN_RANKING_CUSTOM_RANKS_SD_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_SD_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_SD_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_SD_FETCH:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_SD_RANK=${RIVEN_RANKING_CUSTOM_RANKS_SD_RANK:--120}
      - RIVEN_RANKING_CUSTOM_RANKS_BLURAY_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_BLURAY_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_BLURAY_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_BLURAY_FETCH:-true}
      - RIVEN_RANKING_CUSTOM_RANKS_BLURAY_RANK=${RIVEN_RANKING_CUSTOM_RANKS_BLURAY_RANK:-80}
      - RIVEN_RANKING_CUSTOM_RANKS_HDR_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_HDR_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_HDR_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_HDR_FETCH:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_HDR_RANK=${RIVEN_RANKING_CUSTOM_RANKS_HDR_RANK:-80}
      - RIVEN_RANKING_CUSTOM_RANKS_HDR10_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_HDR10_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_HDR10_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_HDR10_FETCH:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_HDR10_RANK=${RIVEN_RANKING_CUSTOM_RANKS_HDR10_RANK:-90}
      - RIVEN_RANKING_CUSTOM_RANKS_DOLBY_VIDEO_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_DOLBY_VIDEO_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_DOLBY_VIDEO_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_DOLBY_VIDEO_FETCH:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_DOLBY_VIDEO_RANK=${RIVEN_RANKING_CUSTOM_RANKS_DOLBY_VIDEO_RANK:--100}
      - RIVEN_RANKING_CUSTOM_RANKS_DTS_X_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_DTS_X_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_DTS_X_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_DTS_X_FETCH:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_DTS_X_RANK=${RIVEN_RANKING_CUSTOM_RANKS_DTS_X_RANK:-0}
      - RIVEN_RANKING_CUSTOM_RANKS_DTS_HD_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_DTS_HD_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_DTS_HD_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_DTS_HD_FETCH:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_DTS_HD_RANK=${RIVEN_RANKING_CUSTOM_RANKS_DTS_HD_RANK:-0}
      - RIVEN_RANKING_CUSTOM_RANKS_DTS_HD_MA_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_DTS_HD_MA_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_DTS_HD_MA_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_DTS_HD_MA_FETCH:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_DTS_HD_MA_RANK=${RIVEN_RANKING_CUSTOM_RANKS_DTS_HD_MA_RANK:-0}
      - RIVEN_RANKING_CUSTOM_RANKS_ATMOS_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_ATMOS_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_ATMOS_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_ATMOS_FETCH:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_ATMOS_RANK=${RIVEN_RANKING_CUSTOM_RANKS_ATMOS_RANK:-0}
      - RIVEN_RANKING_CUSTOM_RANKS_TRUEHD_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_TRUEHD_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_TRUEHD_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_TRUEHD_FETCH:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_TRUEHD_RANK=${RIVEN_RANKING_CUSTOM_RANKS_TRUEHD_RANK:-0}
      - RIVEN_RANKING_CUSTOM_RANKS_DDPLUS_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_DDPLUS_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_DDPLUS_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_DDPLUS_FETCH:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_DDPLUS_RANK=${RIVEN_RANKING_CUSTOM_RANKS_DDPLUS_RANK:-0}
      - RIVEN_RANKING_CUSTOM_RANKS_AAC_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_AAC_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_AAC_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_AAC_FETCH:-true}
      - RIVEN_RANKING_CUSTOM_RANKS_AAC_RANK=${RIVEN_RANKING_CUSTOM_RANKS_AAC_RANK:-70}
      - RIVEN_RANKING_CUSTOM_RANKS_AC3_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_AC3_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_AC3_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_AC3_FETCH:-true}
      - RIVEN_RANKING_CUSTOM_RANKS_AC3_RANK=${RIVEN_RANKING_CUSTOM_RANKS_AC3_RANK:-50}
      - RIVEN_RANKING_CUSTOM_RANKS_REMUX_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_REMUX_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_REMUX_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_REMUX_FETCH:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_REMUX_RANK=${RIVEN_RANKING_CUSTOM_RANKS_REMUX_RANK:--1000}
      - RIVEN_RANKING_CUSTOM_RANKS_WEBDL_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_WEBDL_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_WEBDL_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_WEBDL_FETCH:-true}
      - RIVEN_RANKING_CUSTOM_RANKS_WEBDL_RANK=${RIVEN_RANKING_CUSTOM_RANKS_WEBDL_RANK:-90}
      - RIVEN_RANKING_CUSTOM_RANKS_REPACK_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_REPACK_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_REPACK_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_REPACK_FETCH:-true}
      - RIVEN_RANKING_CUSTOM_RANKS_REPACK_RANK=${RIVEN_RANKING_CUSTOM_RANKS_REPACK_RANK:-5}
      - RIVEN_RANKING_CUSTOM_RANKS_PROPER_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_PROPER_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_PROPER_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_PROPER_FETCH:-true}
      - RIVEN_RANKING_CUSTOM_RANKS_PROPER_RANK=${RIVEN_RANKING_CUSTOM_RANKS_PROPER_RANK:-4}
      - RIVEN_RANKING_CUSTOM_RANKS_DUBBED_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_DUBBED_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_DUBBED_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_DUBBED_FETCH:-true}
      - RIVEN_RANKING_CUSTOM_RANKS_DUBBED_RANK=${RIVEN_RANKING_CUSTOM_RANKS_DUBBED_RANK:-1}
      - RIVEN_RANKING_CUSTOM_RANKS_SUBBED_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_SUBBED_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_SUBBED_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_SUBBED_FETCH:-true}
      - RIVEN_RANKING_CUSTOM_RANKS_SUBBED_RANK=${RIVEN_RANKING_CUSTOM_RANKS_SUBBED_RANK:-4}
      - RIVEN_RANKING_CUSTOM_RANKS_AV1_ENABLED=${RIVEN_RANKING_CUSTOM_RANKS_AV1_ENABLED:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_AV1_FETCH=${RIVEN_RANKING_CUSTOM_RANKS_AV1_FETCH:-false}
      - RIVEN_RANKING_CUSTOM_RANKS_AV1_RANK=${RIVEN_RANKING_CUSTOM_RANKS_AV1_RANK:-0}

      # Indexer
      - RIVEN_INDEXER_UPDATE_INTERVAL=${RIVEN_INDEXER_UPDATE_INTERVAL:-3600}
    volumes:
      - ./data:/riven/data
      - /mnt:/mnt
