services:
  riven:
    image: spoked/iceberg:latest
    container_name: riven
    restart: unless-stopped
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - ORIGIN=http://localhost:3000
      - TZ=America/New_York
    volumes:
      - ./data:/riven/data
      - /mnt:/mnt
    ports:
      - "3000:3000"
